spring.application.name=ERPSpring
logging.level.web=debug
logging.level.org.springframework.jdbc.core=debug

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=ZRB_ERP
spring.datasource.password=ZRB_ERP