spring.application.name=ERPSpring

spring.datasource.url=jdbc:postgresql://localhost:5432/northwind
spring.datasource.username=erp_user
spring.datasource.password=erp_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false